name: Deploy Dev

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      #      - name: Install NPM Dependencies
      #        run: npm install
      #      - name: Run Build Task
      #        run: npm run build
      #      - name: Create Deployment Folder
      #        run: mkdir deploy && cp -r .nuxt deploy/.nuxt && cp -r node_modules deploy/node_modules && cp -r static deploy/static && cp -r assets deploy/assets
      - name: Remove Some Files
        run: rm -fr .??*
       steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BLOG_API_URL: "https://dev-blog-api.mattcrandell.com"
          envkey_APP_URL: "https://dev.mattcrandell.com"
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: './'
          REMOTE_HOST: 64.4.160.12
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: 7822
          TARGET: /var/www/portfolio/frontend-dev
      - name: Run and Build
        uses: appleboy/ssh-action@master
        with:
          host: 64.4.160.12
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 7822
          script: |
            cd /var/www/portfolio/frontend-dev
            npm install
            npm run build
