name: Deploy Dev

on:
  push:
    branches:
      - "develop"
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      #      - name: Install NPM Dependencies
      #        run: npm install
      #      - name: Run Build Task
      #        run: npm run build
      #      - name: Create Deployment Folder
      #        run: mkdir deploy && cp -r .nuxt deploy/.nuxt && cp -r node_modules deploy/node_modules && cp -r static deploy/static && cp -r assets deploy/assets
      - name: Remove Some Files
        run: rm -fr .??*
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BLOG_API_URL: "https://dev-blog-api.mattcrandell.com"
          envkey_APP_URL: "https://dev.mattcrandell.com"
          envkey_GOOGLE_ANALYTICS_ID: "G-2QS101YB7D"
          envkey_INVISIBLE_RECAPTCHA_SITEKEY: ${{ secrets.ENVKEY_INVISIBLE_RECAPTCHA_SITEKEY }}
          envkey_INVISIBLE_RECAPTCHA_SECRETKEY: ${{ secrets.ENVKEY_INVISIBLE_RECAPTCHA_SECRETKEY }}
          envkey_MAILGUN_DOMAIN: ${{ secrets.ENVKEY_MAILGUN_DOMAIN }}
          envkey_MAILGUN_SECRET: ${{ secrets.ENVKEY_MAILGUN_SECRET }}
          envkey_MAILGUN_API: ${{ secrets.ENVKEY_MAILGUN_API }}
      #- name: Deploy to Server
      #  uses: appleboy/scp-action@v0.1.4
      #  with:
      #    host: 45.4.172.174
      #    username: ${{ secrets.SSH_USERNAME }}
      #    password: ${{ secrets.SSH_PASSWORD }}
      #    port: 7822
      #    source: './'
      #    target: /var/www/portfolio/frontend-dev
      # - name: Deploy to Server
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: '-rltgoDzvO --delete'
      #     SOURCE: './'
      #     REMOTE_HOST: 64.4.160.12
      #     REMOTE_USER: ${{ secrets.SSH_USERNAME }}
      #     REMOTE_PORT: 7822
      #     TARGET: /var/www/portfolio/frontend-dev
      - name: Create SSH key
        run: |
          which ssh-agent || (sudo apk update && sudo apk add openssh-client)
          which rsync || (sudo apk update && sudo apk add rsync)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/private.key
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/private.key
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/private.key
          # Append keyscan output into known hosts
          ssh-keyscan 45.4.172.174 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      #- name: Create SSH key
      #  run: |
      #    install -m 600 -D /dev/null ~/.ssh/id_rsa
      #    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #    echo "45.4.172.174" > ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/private.key
          echo "Deploy to dev environment"
          rsync -rltgoDzvO --delete 'ssh -p 7822' ./ deploy@45.4.172.174:/var/www/portfolio/frontend-dev
      - name: Run and Build
        uses: appleboy/ssh-action@master
        with:
          host: 45.4.172.174
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 7822
          script: |
            cd /var/www/portfolio/frontend-dev
            npm install
            npm run build
            pm2 reload PortfolioDev
