name: Deploy Dev

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install NPM Dependencies
        run: npm install
      - name: Run Build Task
        run: npm run build
      - name: Create Deployment Folder
        run: mkdir deploy && cp -r .nuxt deploy/.nuxt && cp -r node_modules deploy/node_modules
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'deploy/'
          REMOTE_HOST: 64.4.160.12
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: 7822
          TARGET: /var/www/portfolio/frontend-dev
