name: Deploy Prod

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Remove Some Files
        run: rm -fr .??*
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BLOG_API_URL: "https://blog-api.mattcrandell.com"
          envkey_APP_URL: "https://www.mattcrandell.com"
          envkey_GOOGLE_ANALYTICS_ID: "G-2QS101YB7D"
          envkey_INVISIBLE_RECAPTCHA_SITEKEY: ${{ secrets.ENVKEY_INVISIBLE_RECAPTCHA_SITEKEY }}
          envkey_INVISIBLE_RECAPTCHA_SECRETKEY: ${{ secrets.ENVKEY_INVISIBLE_RECAPTCHA_SECRETKEY }}
          envkey_MAILGUN_DOMAIN: ${{ secrets.ENVKEY_MAILGUN_DOMAIN }}
          envkey_MAILGUN_SECRET: ${{ secrets.ENVKEY_MAILGUN_SECRET }}
          envkey_MAILGUN_API: ${{ secrets.ENVKEY_MAILGUN_API }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -p 7822 -H 45.4.172.174 >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -rltgoDzvO --delete -e 'ssh -p 7822' ./ ${{ secrets.SSH_USERNAME }}@45.4.172.174:/var/www/portfolio/frontend-prod
      - name: Run and Build
        uses: appleboy/ssh-action@master
        with:
          host: 45.4.172.174
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 7822
          script: |
            cd /var/www/portfolio/frontend-prod
            npm install
            npm run build
            pm2 reload PortfolioProd
